### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by felipecruz91** [alexei-led/pumba#105]
Hi,

**Environment**
OS: Windows 10
Platform: x64

**Steps**
1. Download the binary `pumba_windows_amd64.exe` from release `v0.6.0`.
2. Rename it to `pumba.exe`
3. Add it to the Windows `PATH`.
4. Start Docker.
5. Run some containers.
6. Run `pumba --random --interval 10m kill --signal SIGSTOP`

**Output**

![image](https://user-images.githubusercontent.com/15997951/48311016-f3085780-e598-11e8-8dbe-d7e6ecdf3a1d.png)

**Comment by alexei-led** [comment]
Hi @felipecruz91 

Never tried `pumba` on Windows, but it supposed to work. Under the hood it uses Docker API and AFAIK it's the same for all platforms. 
I think the `pumba` fails due to the "defaults" options. It tries to use `unix:///var/run/docker.sock` socket to connect to the local Docker daemon and Windows does not support communication through unix sockets. Try to use `--host` command option or specify Docker host with `DOCKER_HOST` environment variable. 

Let me know if it works, so I could close the issue. 

Thank you

**Comment by felipecruz91** [comment]
Hi,

It seems that exposing the daemon and setting the `DOCKER_HOST` environment variable made it work.

Thanks @alexei-led 

![image](https://user-images.githubusercontent.com/15997951/48311580-108def00-e5a2-11e8-901d-7f78f6af5dab.png)


![image](https://user-images.githubusercontent.com/15997951/48311590-31564480-e5a2-11e8-97cb-837484207076.png)

**Comment by PanosGreg** [comment]
Since on **Windows Server 2019** there's no docker desktop, here's what I did which worked fine
based on the @felipecruz91 note's

- Create a docker config in `C:\ProgramData\docker\config\daemon.json`
```json
{
    "group" : "docker_users",
    "hosts": ["tcp://0.0.0.0:2375", "npipe://"]
}
```
> Note: I have a local user group called `docker_users` so that I don't have to run everything as admin 
- restart the docker engine (in order for the new config to take effect)
```powershell
Restart-Service docker
```
- add a system variable (need to run PS console as admin)
```powershell
$EnvName  = 'DOCKER_HOST'
$EnvValue = 'tcp://localhost:2375'
[Environment]::SetEnvironmentVariable($EnvName, $EnvValue, 'Machine')
refreshenv
```
> Note: you need choco installed in order to have the "refreshenv" command

You can finally run pumba on windows server without any issue. When you try pumba --help, you should NOT see an error at the end like so:
`time="2021-08-07T14:20:57+01:00" level=fatal msg="protocol not available"`
