### ISSUE TITLE
Pumba daemonset pods are crashing

### ISSUE THREAD

**Issue by yaron-idan** [alexei-led/pumba#110]
Trying to deploy k8s daemonset using this [example](https://github.com/alexei-led/pumba/blob/master/deploy/pumba_kube.yml) (after fixing it using the suggestion here - https://github.com/alexei-led/pumba/issues/42#issuecomment-324774706). 
When I try to run the docker container locally (`gaiaadm/pumba:master`) I get the same error, which is `No help topic for 'pumba'` no matter what command I try to execute.
Any idea what might be causing this?

**Comment by alexei-led** [comment]
The Docker image entrypoint had been changed to the `pumba` binary, since image created from SCRATCH now and doesn’t contain any shell as an entrypoint.

Try to run commands directly, like:

`docker run -it gaiaadm/pumba:master version`

Also, it’s better to use version tag, instead of `master` to avoid breaking changes in future.

**Comment by yaron-idan** [comment]
That works. Thanks! 
Great name for a product, BTW.
WDYT about changing the kube-deploy example to reflect this change?
