### ISSUE TITLE
Attacking a container's available cpu/ram?

### ISSUE THREAD

**Issue by adamdavis40208** [alexei-led/pumba#114]
pumba's tagline is "Chaos testing and network emulation tool for Docker." Does resource exhaustion fit under this umbrella?

I'm currently researching different ways of accomplishing this with docker/linux base images.

I'm not sure what is readily available yet (without pre-installing agents to do the actual attacks, or relying on distro specific tools), but I'm curious what your thoughts are on the topic.

Thanks in advance!

**Comment by alexei-led** [comment]
@adamdavis40208 I have plans to add such capability to `pumba`. The first idea was to "inject" `stress` or `stress-ng` process into victim container and using stress tool to simulate a workload on CPU, memory and IO.
Currently, I'm thinking about different approach. Instead of simulating workload, try to "starve" container, by changing allocated resources: reducing CPU, memory and IO. Thus process running within victim container, will "hunger" for missing resources and this "hunger" should impact on overall system behaviour in a slimialr way as a "simulated" workload.

p.s.: I still did not start the implementation, but hope to implement this in one of upcoming releases

**Comment by adamdavis40208** [comment]
What are you ideas for approaching this? I have some cycles to spare, we can use it for a discussion launch if anything

**Comment by alexei-led** [comment]
Done. Injecting `stress-ng` into target container `cgroups` did the trick.
