### ISSUE TITLE
pumba netem is affecting all containers in host and not responding to kill -9 when running in background

### ISSUE THREAD

**Issue by sayankc** [alexei-led/pumba#147]
Hi,
I ran one docker container. Here is the output.
`[root@XXX ~]# docker ps -a
CONTAINER ID        IMAGE                                                               COMMAND                  CREATED             STATUS              PORTS                    NAMES
506399108abe        selenium/node-chrome:3.141.59-krypton   "/opt/bin/entry_po..."   51 minutes ago      Up 9 minutes        0.0.0.0:6464->6464/tcp   node_chrome_2_1
38a7191aa367        selenium/node-chrome:3.141.59-krypton   "/opt/bin/entry_po..."   51 minutes ago      Up 9 minutes        0.0.0.0:6363->6363/tcp   node_chrome_1_1
`
Then I applied network delay on it.

`nohup pumba_linux_amd64 netem --duration 5m --tc-image registry-all.docker.ing.net/gaiadocker/iproute2 delay --time 1000  re2:node*2* &`

Also tried following .
`pumba_linux_amd64 netem --duration 5m --tc-image registry-all.docker.ing.net/gaiadocker/iproute2 delay --time 1000  re2:node*2* &`

All docker containers became slow (node_chrome_2_1 & node_chrome_1_1). --> **not expected.**

Then killed the pumba process by issuing following command.
`kill -9 <pid of the process>`

Expected : Response time for APIs within node_chrome_2_1 & node_chrome_1_1 container will be back to normal.
_Actual : Still the APIs are slow. 
1.Before starting pumba , Resposne was ~ 300 ms
2.During pumba net , response time was ~ 6-7s
3.After killing pumba netem command , response time was ~ 6-7s
--> not expected #3_

**Comment by sayankc** [comment]
Same is happening if I use pumba container. 
However, **found one work around** .
Once pumba netem is killed/ stopped , if we restart docker , the response time comes back to normal.
`service docker restart`

**Comment by alexei-led** [comment]
@sayankc Hello, I have some questions and recommendations:
1. What Docker networking mode are you using for your containers? bridge? host? overlay? other?
2. killing Linux process with SIGKILL (9) prevents `pubma` from proper handling stop signal (SIGKILL cannot be intercepted) - use SIGTERM (15) then `pumba` will reset network emulation before exit
3. `pumba` uses Linux kernel traffic control netem and applies it to the default network interface of the target container. So, if the same network interface is used by other containers on host they will be affected. That's why I've asked question 1 (above)

**Comment by sayankc** [comment]
Ah! It is clear now. My configuration was missing network separation.
Once the containers are spawned in separate networks , and SIGTERM is used , `pumba` is exiting gracefully.
