### ISSUE TITLE
Any Plan about Network Partitioning Simulation?

### ISSUE THREAD

**Issue by LiangShang** [alexei-led/pumba#96]
while trying [blockade](https://github.com/worstcase/blockade), I found that they could simulate network partitioning from containers to containers, which is a feature I fail to find from pumba. So is network partitioning simulation taken into development plan? Or will a PR on this be discussable?

**Comment by alexei-led** [comment]
You can use Pumba to achieve the same. Both `blockade` and `pumba` use the same `tc` tool to shape network traffic.
The big difference is that Pumba does not launch containers, you are responsible to launch them with CLI, API, compose, swarm, Kubernetes or other way. 
In order to "partition" network between 2 containers, select network emulation you would like to use (like "drop packets" or "increase latency" or other) and shape outbound traffic for each container (you can specify target IP, if you like to affect only on specific connection).

**Comment by LiangShang** [comment]
I mean, the network partitioning described below. blockade could divide containers into several "subnets", in which the containers could communicate with each other while among the "subnets" the network is broken.

`blockade partition n1,n2 n3,n4`

>  Create one or more network partitions. Each partition is specified as a comma-separated list. Containers may not exist in more than one partition. Containers not specified are grouped into an implicit partition. Each partition command replaces any previous partition or block rules.
